/*-----------------------------------------------------------------------------*/
/*    Distributed by Wireless Innovation Forum                                 */
/*    Copyright 2021 SDS Transceiver WG Transceiver Next Task Group.           */
/*    All Rights Reserved.                                                     */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/* https://github.com/Wireless-Innovation-Forum/Facilities/blob/master/LICENSE */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*-----------------------------------------------------------------------------*/
/* Title : ScaXcvrBurstControlRelativeCreation.idl                             */
/* Date:  25 December 2021                                                     */
/* Version: V2.1.0                                                             */
/* Purpose: The ScaXcvrBurstControlRelativeCreation.idl file is specified as   */
/*          the IDL file that declares the BurstControl RelativeCreation       */
/*          service interface specified by section 3.1.4 of Transceiver        */
/*          Facility PIM Specification                                         */
/*-----------------------------------------------------------------------------*/

#ifndef __SCA_XCVR_BURST_CONTROL_RELATIVE_CREATION_DEFINED
#define __SCA_XCVR_BURST_CONTROL_RELATIVE_CREATION_DEFINED

#include "ScaXcvrBurstControlTypes.idl"

module WInnF_Sca
{
  module Transceiver
  {
    module BurstControl
    {
      interface RelativeCreation
      {
        void scheduleRelativeBurst(in boolean requestedAlternate,
                                   in Delay requestedDelay,
                                   in BlockLength requestedLength)
          raises( UnavailableService,
                 NoAlternateReferencing,
                 MinFromPrevious,
                 MaxFromPrevious,
                 MinBlockLength,
                 MaxBlockLength,
                 RelativeMILT);
      };
    };  
  }; //Transceiver
}; // WInnF_Sca

#endif // __SCA_XCVR_BURST_CONTROL_RELATIVE_CREATION_DEFINED