/*-----------------------------------------------------------------------------*/
/*    Distributed by Wireless Innovation Forum                                 */
/*    Copyright 2021 SDS Transceiver WG Transceiver Next Task Group.           */
/*    All Rights Reserved.                                                     */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/* https://github.com/Wireless-Innovation-Forum/Facilities/blob/master/LICENSE */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*-----------------------------------------------------------------------------*/
/* Title : ScaXcvrTuningTypes.idl                                              */
/* Date:  25 December 2021                                                     */
/* Version: V2.1.0                                                             */
/* Purpose: The ScaXcvrTuningInitialTuning.idl file is specified as the IDL    */
/*          file that declares the InitialTuning service interface specified   */
/*          by sections 3.1.11 of Transceiver Facility PIM Specification       */
/*-----------------------------------------------------------------------------*/

#ifndef __SCA_XCVR_TUNING_INITIAL_TUNING_DEFINED
#define __SCA_XCVR_TUNING_INITIAL_TUNING_DEFINED

#include "ScaXcvrTuningTypes.idl"

module WInnF_Sca
{
  module Transceiver
  {
    //InitialTuning Types
    typedef unsigned short TuningPreset;
    const TuningPreset UNDEFINED_TUNING_PRESET = 0xFFFF;

    module Tuning
    {
      interface InitialTuning
      {
        void setTuning(in TuningPreset requestedPreset,
                       in CarrierFreq requestedFrequency,
                       in Gain requestedGain,
                       in BurstNumber scheduleAbsoluteBurst)
          raises( UnavailableService,
                 MaxTuningPreset,
                 MinCarrierFreq,
                 MaxCarrierFreq,
                 MinGain,
                 MaxGain,
                 TuningMILT);
      };
    };
  }; //Transceiver
}; // WInnF_Sca

#endif // __SCA_XCVR_TUNING_INITIAL_TUNING_DEFINED