/*-----------------------------------------------------------------------------*/
/*    Distributed by Wireless Innovation Forum                                 */
/*    Copyright 2021 SDS Transceiver WG Transceiver Next Task Group.           */
/*    All Rights Reserved.                                                     */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/* https://github.com/Wireless-Innovation-Forum/Facilities/blob/master/LICENSE */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*-----------------------------------------------------------------------------*/
/* Title : ScaXcvrTypes.idl                                                    */
/* Date:  25 December 2021                                                     */
/* Version: V2.1.0                                                             */
/* Purpose: The ScaXcvrTypes.idl file is specified as the IDL file that        */
/*          declares the types specified by section 3.4 of Transceiver         */
/*          Facility PIM  Specification                                        */
/*-----------------------------------------------------------------------------*/

#ifndef __SCA_XCVR_TYPES_DEFINED
#define __SCA_XCVR_TYPES_DEFINED

#include "ScaXcvrExceptions.idl"

module WInnF_Sca
{
  module Transceiver
  {
    //Gain
    typedef short Gain; // in 1/10 dB
    const Gain UNDEFINED_GAIN = 0x7FFF;

    // Delay   
    typedef unsigned long long DelayType;
    typedef DelayType Delay;  // in ns

    const Delay UNDEFINED_DELAY = 0x7FFFFFFFFFFFFFFF;  // 9223372036854775807

    // BurstNumber
    typedef unsigned long BurstNumber;


    // TimeSpec 
    struct TimeSpec
    {
      unsigned long seconds;             // in seconds
      unsigned long nanoseconds;         // in nanoseconds (<1.000.000.000)
    };
    
    // A TimeSpec with an undefined value shall have both, the seconds and the
    // nanoseconds, fields set to UNDEFINED_TIME_SPEC_TIME
    const unsigned long UNDEFINED_TIME_SPEC_TIME = 0xFFFFFFFF; 

  }; // Transceiver
}; // WInnF_Sca

#endif // __SCA_XCVR_TYPES_DEFINED
