/*-----------------------------------------------------------------------------*/
/*    Distributed by Wireless Innovation Forum                                 */
/*    Copyright 2021 SDS Transceiver WG Transceiver Next Task Group.           */
/*    All Rights Reserved.                                                     */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/* https://github.com/Wireless-Innovation-Forum/Facilities/blob/master/LICENSE */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*-----------------------------------------------------------------------------*/
/* Title : ScaXcvrNotifications.idl                                            */
/* Date:  25 December 2021                                                     */
/* Version: V2.1.0                                                             */
/* Purpose: The ScaXcvrNotifications.idl file is specified as the IDL file     */
/*          that declares the Notifications service interfaces specified by    */
/*          sections 3.1.13 and 3.1.14 of Transceiver Facility PIM             */
/*          Specification                                                      */
/*-----------------------------------------------------------------------------*/

#ifndef __SCA_XCVR_NOTIFICATIONS_DEFINED
#define __SCA_XCVR_NOTIFICATIONS_DEFINED

module WInnF_Sca
{
  module Transceiver
  {
    module Notifications
    {
      enum Event
      {
        PROCESSING_START_EVENT,
        PROCESSING_STOP_EVENT,
        SILENCE_START_EVENT,
        SILENCE_STOP_EVENT
      };
    
      enum Error
      {
        DELAYED_TUNING_ERROR,
        TUNING_TIMEOUT_ERROR,
        DELAYED_FIRST_SAMPLE_ERROR,
        FIRST_SAMPLE_TIMEOUT_ERROR,
        TRANSMISSION_UNDERFLOW_ERROR,
        RECEPTION_OVERFLOW_ERROR,
        SHORTER_TRANSMITTED_BLOCK_ERROR,
        LONGER_TRANSMITTED_BLOCK_ERROR
      };

      interface Events
      {
        void notifyEvent(in Event notifiedEvent);
      };
                      
      interface Errors
      {
        void notifyError(in Error notifiedError);
      };
    };
  }; //Transceiver
}; // WInnF_Sca

#endif // __SCA_XCVR_NOTIFICATIONS_DEFINED